info:
  component: Hystrix-Dashboard-With-Turbine

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 7979

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    com.netflix.turbine: INFO